#!/bin/bash
IFS='-'
_time="$(date "+%Y-%m-%d %H:%M:%S")"
_date="$(date "+%Y-%m-%d")"
_title="$@"
_filename="$_date-$*.markdown"

if [ $# -eq 0 ]; then
  echo "Usage $0 [Title of post]"
  exit 1
fi

basepost="---
layout:     post
title:      \"$_title\"
date:       $_time
exerpt:     \"\"
categories: blog
---

"

_dirname="_posts"
if [ "${PWD##*/}" == "_posts" ]; then
  _dirname="."
fi

file="$_dirname/$_filename"
echo "$basepost" > "$file"

$EDITOR "$file"
